plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO Stuff
author: Bradley Taunt
title: 512KB Club
tagline: A showcase of lightweight websites.
description: The 512KB Club is an exclusive list of web pages weighing less than 512 kilobytes.
lang: en
locale: en_CA
url: "https://512kb.club"
baseurl: ""
permalink: :title
timezone: Etc/GMT
host: 0.0.0.0

# Syntax Highlighting
highlighter: rouge

exclude:
  - scripts/
